# Generated by Django 4.0.5 on 2022-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aktay_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Актау',
                'verbose_name_plural': 'Актау',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='aktobe_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Актобе',
                'verbose_name_plural': 'Актобе',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='almaty_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Алматы',
                'verbose_name_plural': 'Алматы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='astana_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Астана',
                'verbose_name_plural': 'Астана',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='karaganda_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Караганда',
                'verbose_name_plural': 'Караганда',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='kostanay_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Костанай',
                'verbose_name_plural': 'Костанай',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('age', models.CharField(choices=[('young', 'Молодой (до 18 лет)'), ('mature', 'Зрелый (от 19 до 34 лет)'), ('middile', 'Средний (от 35 до 59 лет)'), ('old', 'Пожилой (от 60 до 74 лет)')], max_length=150, verbose_name='Возраст')),
                ('city', models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('aktay', 'Актау'), ('aktobe', ''), ('karaganda', ''), ('kostanay', ''), ('turkestan', 'Туркестан'), ('shymkent', '')], max_length=150, verbose_name='Город')),
                ('needed_type', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический'), ('nature', 'Природный'), ('culture', 'Культурный')], max_length=150, verbose_name='Тип')),
                ('needed_time', models.CharField(blank=True, choices=[('less30', 'до 30 минут'), ('less50', 'от 30 до 50 минут'), ('less90', 'от 50 минут до 1,5 часов'), ('more90', 'от 1,5 часов и более')], max_length=20, verbose_name='Время')),
                ('recomendations', models.CharField(blank=True, max_length=2000, verbose_name='Рекомендации')),
            ],
            options={
                'verbose_name': 'Короче юзер',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='shymkent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Щымкент',
                'verbose_name_plural': 'Шымкент',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='turkestan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('typeofwonder', models.CharField(choices=[('funny', 'Отдых и развлечения'), ('history', 'Исторический тип'), ('nature', 'Природный тип'), ('culture', 'Культурный тип')], max_length=150, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='almaty', verbose_name='Картинка')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('is_any', models.BooleanField(default=False, verbose_name='Для всех возрастов')),
                ('is_young', models.BooleanField(default=False, verbose_name='Для Молодой (до 18 лет)')),
                ('is_mature', models.BooleanField(default=False, verbose_name='Зрелый (от 19 до 34 лет)')),
                ('is_middle', models.BooleanField(default=False, verbose_name='Средний (от 35 до 59 лет)')),
                ('is_old', models.BooleanField(default=False, verbose_name='Пожилой (от 60 до 74 лет)')),
                ('time', models.IntegerField(verbose_name='Время до точки с центра города (в минутах)')),
            ],
            options={
                'verbose_name': 'Туркестан',
                'verbose_name_plural': 'Туркестан',
                'ordering': ['-id'],
            },
        ),
    ]
