# Generated by Django 4.0.5 on 2022-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktay_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='aktay', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='aktobe_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='aktobe', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='astana_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='astana', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='karaganda_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='karaganda', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='kostanay_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='kostanay', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='shymkent_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='shymkent', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='turkestan_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='turkestan', verbose_name='Картинка'),
        ),
    ]
